# Project Configuration File
# --------------------------

dataset:
    name: Loan-Risk-Optimizer
    data_path: data/heloc.csv
    feature_descriptions:
        RiskPerformance: Paid as negotiated flag (12-36 months). String of Good and Bad
        ExternalRiskEstimate: Consolidated version of risk markers
        MSinceOldestTradeOpen: Months Since Oldest Trade Open
        MSinceMostRecentTradeOpen: Months Since Most Recent Trade Open
        AverageMInFile: Average Months in File
        NumSatisfactoryTrades: Number of credit agreements with on-time payments
        NumTrades60Ever2DerogPubRec: Number of trade lines 60 days past due date, includes derogatory public records
        NumTrades90Ever2DerogPubRec: Number of trade lines 90 days past due date, includes derogatory public records
        NumTotalTrades: Total number of credit accounts
        NumTradesOpeninLast12M: Number of Trades Open in Last 12 Months
        PercentTradesNeverDelq: Percent Trades Never Delinquent
        MSinceMostRecentDelq: Months Since Most Recent Delinquency
        MaxDelq2PublicRecLast12M: Maximum Delinquency/Public Records Last 12 Months
        MaxDelqEver: Maximum Delinquency Ever
        PercentInstallTrades: Percent Installment Trades
        NetFractionInstallBurden: Net Fraction Installment Burden. Installment balance/original loan amount
        NumInstallTradesWBalance: Number Installment Trades with Balance
        MSinceMostRecentInqexcl7days: Months Since Most Recent Inquiry excluding 7 days
        NumInqLast6M: Number of Inquiries in Last 6 Months
        NumInqLast6Mexcl7days: Number of Inquiries in Last 6 Months excluding 7 days
        NetFractionRevolvingBurden: Net Fraction Revolving Burden. Revolving balance/credit limit
        NumRevolvingTradesWBalance: Number Revolving Trades with Balance
        NumBank2NatlTradesWHighUtilization: Number of credit cards with balance ≥ 75% of its limit
        PercentTradesWBalance: Percent Trades with Balance

outputs:
    path: ./outputs

models:
  logistic_regression:
    solver: ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
    C: [0.001, 0.01, 0.1, 1, 10, 100]
    max_iter: [100, 200, 300, 400, 500]

  random_forest:
    n_estimators: [100, 200, 500, 1000, 2000]
    max_features: ['log2', 'sqrt']
    max_depth: [10, 20, 30, 40, 50]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    bootstrap: [True, False]

  xgboost:
    learning_rate: [0.01, 0.05, 0.1, 0.2]
    n_estimators: [100, 200, 500, 1000]
    max_depth: [3, 4, 5, 6, 7, 8]

  catboost:
    iterations: [100, 200, 500, 1000]
    learning_rate: [0.01, 0.05, 0.1, 0.2]
    depth: [3, 4, 5, 6, 7, 8]

